### ISSUE TITLE
Converting qwen-7b-chat model is failed 

### ISSUE THREAD

**Issue by ke-feng** [OpenVINO-dev-contest/Qwen2.openvino#1]
Problem description:
----
With this repo and the model https://huggingface.co/Qwen/Qwen-7B-Chat,  Converting model is failed finally.

Hardware:
----
```
3rd gen  Intel Xeon;
32 vCPU, 64GB RAM;
```

Problem reproduced steps:
----
```
1.  Download the model to local machine: 
     https://huggingface.co/Qwen/Qwen-7B-Chat/tree/main  ->  /opt/fm_openvino/Qwen-7B-Chat

2.  Download the OpenVINO convert tool to local machine: 
     https://github.com/OpenVINO-dev-contest/Qwen2.openvino  -> /opt/Qwen2.openvino

3.  Setup environment with the following commands:
4. 
     conda create -n qwen-7b-chat-ov python=3.10 -y
     conda activate qwen-7b-chat-ov

     cd /opt/Qwen2.openvino
     pip install wheel setuptools
     pip install -r requirements.txt

     # convert model:
     cd /opt/Qwen2.openvino
     python3 convert.py --model_id /opt/fm_openvino/Qwen-7B-Chat --precision int4 --output /opt/fm_openvino/Qwen-7B-Chat-ov

     # Getting the following error and converting model is failed finally.

(qwen-7b-chat-ov) root@ai-qwen:/opt/Qwen2.openvino# python3 convert.py --model_id /opt/fm_openvino/Qwen-7B-Chat --precision int4 --output /opt/fm_openvino/Qwen-7B-Chat-ov
INFO:nncf:NNCF initialized successfully. Supported frameworks detected: torch, onnx, openvino
====Exporting IR=====
Traceback (most recent call last):
  File "/opt/Qwen2.openvino/convert.py", line 53, in <module>
    ov_model = OVModelForCausalLM.from_pretrained(args.model_id, export=True,
  File "/root/miniconda3/envs/qwen-7b-chat-ov/lib/python3.10/site-packages/optimum/modeling_base.py", line 359, in from_pretrained
    config = AutoConfig.from_pretrained(
  File "/root/miniconda3/envs/qwen-7b-chat-ov/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1141, in from_pretrained
    trust_remote_code = resolve_trust_remote_code(
  File "/root/miniconda3/envs/qwen-7b-chat-ov/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 622, in resolve_trust_remote_code
    raise ValueError(
ValueError: Loading /opt/fm_openvino/Qwen-7B-Chat/config.json requires you to execute the configuration file in that repo on your local machine. Make sure you have read the code there to avoid malicious use, then set the option `trust_remote_code=True` to remove this error.
```

**Comment by openvino-dev-samples** [comment]
hi @kefeng-ai this repository only works for QWEN2.

For QWEN1, you should add followed config parameter in `OVModelForCausalLM.from_pretrained`
```   
model_kwargs = {
        "trust_remote_code": True,
        "config": AutoConfig.from_pretrained(args.model_id, trust_remote_code=True),
    }
```

**Comment by ke-feng** [comment]
@OpenVINO-dev-contest Thanks!
I switched to Qwen2(Qwen1.5-7B-Chat) model and pulled the latest change of current repo, I get the following error when converting this model, please advise how to fix it, thanks!

```
root@ai-qwen:/opt/Qwen2.openvino# git pull
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 3 (delta 2), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (3/3), 938 bytes | 938.00 KiB/s, done.
From https://github.com/OpenVINO-dev-contest/Qwen2.openvino
   acc1acd..8aae140  main       -> origin/main
Updating acc1acd..8aae140
Fast-forward
 convert.py | 6 +-----
 1 file changed, 1 insertion(+), 5 deletions(-)
(qwen-7b-chat) root@ai-qwen:/opt/Qwen2.openvino#

 root@ai-qwen:/opt/Qwen2.openvino# python3 convert.py --model_id /opt/fm/Qwen1.5-7B-Chat --precision int4 --output /opt/fm_openvino/Qwen1.5-7B-Chat-ov
====Exporting IR=====
Framework not specified. Using pt to export the model.
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.54it/s]
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Using the export variant default. Available variants are:
    - default: The default ONNX variant.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Using framework PyTorch: 2.2.2+cu121
Overriding 1 configuration item(s)
        - use_cache -> True
/root/miniconda3/envs/qwen-7b-chat/lib/python3.10/site-packages/transformers/modeling_utils.py:4225: FutureWarning: `_is_quantized_training_enabled` is going to be deprecated in transformers 4.39.0. Please use `model.hf_quantizer.is_trainable` instead
  warnings.warn(
/root/miniconda3/envs/qwen-7b-chat/lib/python3.10/site-packages/transformers/modeling_attn_mask_utils.py:114: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if (input_shape[-1] > 1 or self.sliding_window is not None) and self.is_causal:
/root/miniconda3/envs/qwen-7b-chat/lib/python3.10/site-packages/optimum/exporters/onnx/model_patcher.py:301: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if past_key_values_length > 0:
/root/miniconda3/envs/qwen-7b-chat/lib/python3.10/site-packages/transformers/models/qwen2/modeling_qwen2.py:126: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if seq_len > self.max_seq_len_cached:
/root/miniconda3/envs/qwen-7b-chat/lib/python3.10/site-packages/transformers/models/qwen2/modeling_qwen2.py:686: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if attention_mask.size() != (bsz, 1, q_len, kv_seq_len):
Traceback (most recent call last):
  File "/opt/Qwen2.openvino/convert.py", line 49, in <module>
    ov_model = OVModelForCausalLM.from_pretrained(args.model_id, export=True,
  File "/root/miniconda3/envs/qwen-7b-chat/lib/python3.10/site-packages/optimum/modeling_base.py", line 401, in from_pretrained
    return from_pretrained_method(
  File "/root/miniconda3/envs/qwen-7b-chat/lib/python3.10/site-packages/optimum/intel/openvino/modeling_decoder.py", line 268, in _from_transformers
    return cls._from_pretrained(
  File "/root/miniconda3/envs/qwen-7b-chat/lib/python3.10/site-packages/optimum/intel/openvino/modeling_decoder.py", line 571, in _from_pretrained
    model = cls.load_model(model_cache_path, quantization_config=None if load_in_4bit else quantization_config)
  File "/root/miniconda3/envs/qwen-7b-chat/lib/python3.10/site-packages/optimum/intel/openvino/modeling_base.py", line 126, in load_model
    model = core.read_model(file_name) if not file_name.suffix == ".onnx" else convert_model(file_name)
  File "/root/miniconda3/envs/qwen-7b-chat/lib/python3.10/site-packages/openvino/runtime/ie_api.py", line 479, in read_model
    return Model(super().read_model(model))
RuntimeError: Exception from src/inference/src/cpp/core.cpp:92:
Exception from src/inference/src/model_reader.cpp:154:
Unable to read the model: /tmp/tmprqaxij7y/openvino_model.xml Please check that model format: xml is supported and the model is correct. Available frontends: tflite tf ir pytorch paddle onnx
```

**Comment by openvino-dev-samples** [comment]
Hi @kefeng-ai could you check if your disk is full ? and also the version of `optimum-intel`

**Comment by ke-feng** [comment]
This issue is resolved after updating the version of optimum-intel, thanks.
